name: Push
on: push

env:
  SLACKSYNC_CHANNEL: 'C012NUFBCLU'
  SLACKSYNC_TOKEN: '${{ secrets.SLACK_TOKEN }}'

jobs:
  prepare:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v1
    - uses: ./

  tests:
    runs-on: ubuntu-24.04
    needs: [prepare]
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm run pack
    - run: export INPUT_GITHUB_TOKEN='${{ secrets.GITHUB_TOKEN }}' npm run test

  conclusion:
    runs-on: ubuntu-24.04
    needs: [tests]
    steps:
    - uses: actions/checkout@v1
    - uses: ./
